### ISSUE TITLE
Remote location mapping system with Estimote?

### ISSUE THREAD

**Issue by PrabakarMP** [Estimote/iOS-Indoor-SDK#12]
Hi,

I read about Estimote beacon and location location mapping system. It is really awesome!

I want to use Estimote beacon and integrate in my app using Estimote SDK. I read about indoor location mapping system and I want to use that effectively in my app. I have a question based on my requirement, I want to place beacons across 2 countries and detect beacon signalling thru some centralised service and provide location mapping path. Is this possible with Estimote beacons and sdk? For ex: I have 10 beacons here in location 1 (country 1), I have another 10 beacons in location 2 (in another country 2). Can I use Estimote and maintain some server to connect all the beacons with some software program and get location mapping system?

Please advise.

**Comment by PrabakarMP** [comment]
Please provide your advise and close it please..

**Comment by Mycek** [comment]
PrabakarMP,

as this is more product question I close this question here on GitHub and encourage you to explore our technical forums (https://forums.estimote.com/c/indoor-location) and continue discussion there :)

Regarding your question - yes it is 100% possible. Since SDK 1.3 you can store locations (ie. all information needed for positioning) in Estimote Cloud and access it from anywhere. So in your situation you would need to map those two locations either from the code with `ESTLocationBuilder` and upload it to the cloud or through our mapping wizard (it is automatically uploaded to cloud then) in the app. Then you can fetch your location by identifier from cloud `fetchLocationByIdentifier:withSuccess:failure:` or if you want to have it more automatic you can make them Public locations (through your Cloud dashboard) and use `fetchNearbyPublicLocationsWithSuccess:failure:`.

**Comment by PrabakarMP** [comment]
Thank you very much! I'll read more on the APIs front and ask you if any doubts.
